language: java
script: make travis

before_script:
  - nvm install node && nvm use node
  - (cd js && npm install -g grunt-cli && npm install)

before_deploy:
  - "sed -i -E -e \"s/0\\.0\\.0/$TRAVIS_TAG/\" js/package.json"

# TODO deploy java artifact here too
# TODO make sure this works now JS is in a subdirectory
deploy:
  provider: npm
  api_key: $NPM_API_KEY
  email: dev@medicmobile.org
  on:
    tags: true
