language: java
script: make travis

before_script:
  - nvm install node && nvm use node
  - (cd js && npm install -g grunt-cli && npm install)

before_deploy:
  - "sed -i -E -e \"s/0\\.0\\.0/$TRAVIS_TAG/\" js/package.json"
